[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "oldest-supported-numpy",
            "cython"]

build-backend = 'setuptools.build_meta'

[[tool.cibuildwheel.overrides]]
select = "pp37-macosx*"
before-build = "pip install -y numpy==1.18"
