[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "oldest-supported-numpy",
            "Cython>=0.29.21,<3.0"]

build-backend = 'setuptools.build_meta'

[tool.cibuildwheel]
# Skip pypy on mac due to numpy/accelerate issues
skip = "pp37* cp36*"
test-requires = "pytest scipy"
test-command = "pytest --pyargs astroscrappy"
