[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "oldest-supported-numpy",
            "Cython>=0.29.21,<3.0"]

build-backend = 'setuptools.build_meta'
