[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "oldest-supported-numpy",
            "cython"]

build-backend = 'setuptools.build_meta'

[tool.cibuildwheel]
# Skip pypy on mac due to numpy/accelerate issues
skip = "pp37-macosx_x86_64"
