name: Run unit tests

on:
  pull_request:
  push:
    branches: [ main ]
    tags:
  workflow_dispatch:

jobs:
  tests:
    name: ${{ matrix.name }} (${{ matrix.os }}, ${{ matrix.toxenv }})
    runs-on: ${{ matrix.os }}
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.7 with required dependencies
            os: macos-latest
            python-version: 3.7
            toxenv: py37-test

          - name: Python 3.8 with required dependencies and measure coverage
            os: ubuntu-latest
            python-version: 3.8
            toxenv: py38-test
            coverage: true

          - name: Python 3.9 with required dependencies
            os: windows-latest
            python-version: 3.9
            toxenv: py39-test

          - name: Python 3.10 with required dependencies
            os: ubuntu-latest
            python-version: "3.10"
            toxenv: py310-test

          - name: Documentation build
            os: ubuntu-latest
            python-version: 3.8
            toxenv: build_docs

          - name: Code style checks
            os: ubuntu-latest
            python-version: 3.8
            toxenv: codestyle

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install tox
    - name: Install graphviz dependency
      if: "endsWith(matrix.toxenv, 'build_docs')"
      run: sudo apt-get -y install graphviz
    - name: Run tests
      if: "! matrix.coverage"
      run: tox -v -e ${{ matrix.toxenv }}
    - name: Run tests with coverage
      if: "matrix.coverage"
      run: |
        pip install Cython extension-helpers numpy
        COVERAGE=1 pip install -e .[test]
        pytest --pyargs astroscrappy docs --cov astroscrappy
    - name: Upload coverage to codecov
      if: "matrix.coverage"
      run: |
        pip install codecov
        codecov

  tests-32bit:
    name: 32-bit
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux1_i686
    steps:
    # TODO: Use newer checkout actions when https://github.com/actions/checkout/issues/334 fixed
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Install dependencies for Python 3.8
      run: /opt/python/cp38-cp38/bin/pip install tox
    - name: Run tests for Python 3.8
      run: /opt/python/cp38-cp38/bin/python -m tox -v -e py38-test -- -sv
